FROM python:3.11-slim

COPY . ./counter_app
WORKDIR counter_app 
RUN pip3 install -r requirements_counter.txt

EXPOSE 4649
CMD ["uvicorn", "counter_app.main:app", "--host", "0.0.0.0", "--port", "4649"]
